spring:
  application:
    name: spring-cloud-product-sel-product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234Asdf
    url: jdbc:mysql://127.0.0.1:3306/food_order?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mappings/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.tee.springcloudsel.springcloudsel.domain  # 注意：对应实体类的路径

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/